# dev
gateway.http.base.url=http://127.0.0.1:10921
gateway.tcp.server=127.0.0.1:30420


# k8s
# gateway.http.base.url=http://guru-im-gateway-http.com:32395
# gateway.tcp.server=guru-im-gateway-tcp.com:31030