spring:
  cloud:
    # Nacos 服务发现与注册配置
    nacos:
      discovery:
        server-addr: 192.168.100.130:8848
        namespace: ${spring.profiles.active}
      config:
        server-addr: 192.168.100.130:8848
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml


  data:
    # Redis配置
    redis:
      host: 192.168.100.130
      port: 6379
      password: redis1234!


## netty配置
im:
  jwt:
    enabled: true
  gateway:
    netty:
      server: ## 服务端，用于与用户通信
        bindAddress: 0.0.0.0
        listenPort: 30420
        serviceName: "${spring.application.name}"  # 支持guru-im-gateway-websocket
        serverBossThreads: 1
        serverWorkerThreads: 3
        serverHandlerThreads: 8
        serverPooledByteBufAllocatorEnable: true
        serverChannelMaxIdleTimeSeconds: 120
        serverAsyncSemaphoreValue: 64
        serverCallbackExecutorThreads: 0
        serverSocketBacklog: 1024
        shutdownWaitTimeSeconds: 3
        useSSL: false
        tlsServerCertPath: ""
        tlsServerKeyPath: ""
        serverHandlerExecutorEnable: true
      client: ## 客户端，用于与分发系统通信
#        bindAddress: 0.0.0.0
#        bindPort: 30430
        clientWorkerThreads: 4
        clientCallbackExecutorThreads: 8
        useSSL: false
        connectTimeoutMillis: 3000
        clientChannelMaxIdleTimeSeconds: 120
        clientAsyncSemaphoreValue: 65535
        lockTimeoutMillis: 3000
        minCloseTimeoutMillis: 100
        sendTimeoutSeconds: 60
        serverServiceName: "guru-im-dispatch"
        reconnectMaxAttempts: 5
        reconnectInitialDelay: 1000
        reconnectMaxDelay: 30000
        reconnectMultiplier: 1.5